import type { Metadata } from "next";
import { Geist, Sora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FoodHub",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, sora.variable)}
    >
      <body className={`${sora.className} min-h-full flex flex-col`}>
        {children}
        </body>
    </html>
  );
}
